name: Build, Test, and Deploy Allure Report

permissions:
  id-token: write
  repository-projects: write
  contents: write

on:
  workflow_dispatch:

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm install
        
      - name: Run Tests
        run: npm test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-history
          
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_history: allure-history
          allure_results: allure-results
          gh_pages: allure-report/allure-report-${{ github.run_number }}
          
      - name: list all files in the directory
        shell: bash
        run: ls -R
        
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh_pages
          publish_dir: allure-history
